# Generated by Django 4.2 on 2024-12-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'taxes'},
        ),
    ]
